[package]
name        = "lesspass"
description = "An efficient implementation of the LessPass password generator."
version     = "0.3.0"
authors     = ["Grégoire Geis <git@gregoirege.is>"]

repository = "https://github.com/71/lesspass.rs"
readme     = "README.md"
license    = "GPL-3.0-only"
edition    = "2018"

keywords = ["cli", "password", "generator"]
categories = ["algorithms", "command-line-utilities"]

[lib]
name = "lesspass"
path = "src/lib.rs"

[[bin]]
name = "lesspass"
path = "src/main.rs"
required-features = [ "default" ]

[dependencies]
bitflags    = "1.2"
hmac        = "0.7"
lazy_static = "1.4"
num-bigint  = "0.2"
num-integer = "0.1"
num-traits  = "0.2"
pbkdf2      = { version = "0.3", default-features = false }
sha2        = { version = "0.8", default-features = false }

atty      = { version = "0.2", optional = true }
rpassword = { version = "4.0", optional = true }
structopt = { version = "0.3", optional = true }

[features]
default = [ "atty", "rpassword", "structopt" ]
